### ISSUE TITLE
capacitance demo

### ISSUE THREAD

**Issue by maasencioh** [mylims/react-demo#3]
- [x] left menu with different demos (#4)
- [x] Drag / drop should indicate that it should be a CSV of IV spectra (title of page) (#4)
- [x] upload a test file (#4)
- [x] center label on the axis (https://github.com/zakodium/react-plot/pull/16)
- [x] add units (https://github.com/cheminfo/iv-spectrum/pull/5)
- [x] display all the variables (#7)
- [x] select buttons choose the variables (#7)
- [x] show markers and plot options (#7)
- [x] export jcamp and previsualize (#7)
- [x] calculate extra information
- [x] react-plot - add tracking
- [x] react-plot - add zoom
